name: Publish Python Package

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: python setup.py sdist bdist_wheel
        
      - name: Publish package
        env:
          user: __token__
          password: ${{ secrets.PIP_TOKEN }}
        run: twine upload dist/*
